### ISSUE TITLE
Why cloud R?

### ISSUE THREAD

**Issue by NadineBestard** [datacarpentry/genomics-r-intro#105]
The content of this lesson is an abreviate version of [R for Reproducible scientific Analysis](http://swcarpentry.github.io/r-novice-gapminder/) with a focus in genomics. However, it is very dependent on the shell lessons intro to understand the data and the AWS setup.

In many other Carpentries lessons there is a big focus in getting students ready to go on their own computers. Recently a carpentries-discuss highlited this as an argument to keep having students install the programs/packages needed instead of using docker images or similar (that could make teaching easier but is less beneficial for the learners).

I had a close look at this lesson and I do not see anything that especially requires big computational steps (unlike genomics-shell). Why not teaching this as [R for Reproducible scientific Analysis](http://swcarpentry.github.io/r-novice-gapminder/)? 

With some modifications this lesson could even be stand alone.  Just teaching R, for people that would like to learn R but is already familiar with the command line and cloud computing. 

I understand this might suppose a big change, at least a first step would add some sections to make it easier to separate from the rest of the Genomics lessons: 
- An intro about the data we will be working with, and store the csv in a way students can download it as it is done with the [gapminder dataset](https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv).
- Add information on the required setup for this lesson in the [lesson itsefl](https://datacarpentry.org/genomics-r-intro/setup.html) (with option A using the instance, option B how to setup for the lesson on own computers). So far the only setup information redirects to the main [workshop setup information](https://datacarpentry.org/genomics-workshop/setup.html) where nothing about this R lesson is stated in the "Option B: use your own computer"  ( This last point is being adressed by #97 )

**Comment by naupaka** [comment]
@NadineBestard the vision is to have this be at the end of the shell-genomics lessons in a sequence, so the data output from those lessons are the inputs to these (since this is a Data Carpentry lesson vs a Software Carpentry lesson, there is more emphasis on integration vs modularity of content). Hence, the use of RStudio Server instead of local R. In a real genomics processing workflow where datasets are larger than the ones used here, there might be a good reason to do the R stuff on a remote server as well.

**Comment by naupaka** [comment]
Thank you for the feedback. The goal of this set of lessons (Data Carpentry Genomics) is specifically to train folks to work on cloud servers. I would direct people who want to have materials focused on doing things locally to the other R lessons hosted by Software Carpentry. I am going to close this since unfortunately we are not planning to change the whole scope for this material.
