### ISSUE TITLE
load tidyverse instead of dplyr in episode 4

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-r-intro#21]
[Episode 4](https://carpentrieslab.github.io/genomics-r-intro/04-dplyr/index.html) has learners install and load dplyr, but then in [episode 5](https://carpentrieslab.github.io/genomics-r-intro/05-data-visualization/index.html) they load the full tidyverse library.

**Comment by ErinBecker** [comment]
And do we need to even have them loading or installing packages, given that they're working on the cloud? I assume these packages are already installed on our AMI image, so maybe they have to load them but not install them?

**Comment by naupaka** [comment]
I think it's best practice to explicitly load each of the needed libraries, instead of tidyverse as a whole. Probably worth going through the process of installing packages at least once -- it's a crucial skill for novices to learn (even though, as you point out, they will likely already be installed on the ami).

**Comment by JasonJWilliamsNY** [comment]
I agree with the idea of having learners install a library. Might I suggest that this could be part of a final episode where we go into CRAN and Bioconductor? We could err on the side of caution/reproducibility by basing important parts of the lesson only on what is preinstalled, and then showing this later.

**Comment by jananiravi** [comment]
@naupaka I generally agree with the thought process behind library requirement & loading practices for R-newbies, but as far as `tidyverse` goes, I think loading the whole suite is more robust than individual packages because of the high level of interdependencies. From the workshops we have conducted so far, it seems like loading this works with far fewer errors than individual ones except when they are running very old R/RStudio. Even in those cases, I'd recommend switching to the new rstudio.cloud w/ tidyverse. Seems to help them seamlessly move from import/export <-> tidying data <-> wrangling <-> dataviz <-> rmd and magittr 
thoughts?

**Comment by JasonJWilliamsNY** [comment]
installing dplyr took a few minutes so an instructor needs to plan for this. Also we don't explain the warnings in the lesson which can be scary for newcomers.

**Comment by aortiz24** [comment]
I'd like to help solve this issue. Is there a specific implementation you had in mind?

**Comment by naupaka** [comment]
Thanks for diving on this, @aortiz24! 

After reading through this and the current rendering of the materials ([here](https://datacarpentry.org/genomics-r-intro/)), my sense is that this issue is now no longer relevant, since with the revision to the lessons episode 5 now uses `ggplot2` directly. I also noticed there's reference to `readxl` in episode 3, which precedes the discussion of packages, which comes in episode 4. The discussion of what a package is and what they are for could be moved up to that point? thoughts @JasonJWilliamsNY?

**Comment by JasonJWilliamsNY** [comment]
I think this is now obsolete @naupaka can you confirm (and close)?

**Comment by naupaka** [comment]
No longer relevant because the new lessons include loading of several packages.
