### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/genomics-r-intro#35]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [ ] Example code chunks run as expected
- [ ] Challenges / exercises run as expected
- [ ] Challenge / exercise solutions are correct
- [ ] Call out boxes (exercises, discussions, tips, etc) render correctly
- [ ] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [ ] Each episode includes learning objectives
- [ ] Each episode includes questions
- [ ] Each episode includes key points
- [ ] Setup instructions are up-to-date, correct, clear, and complete
- [ ] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [ ] Some Instructor notes are provided
- [ ] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hey @JasonJWilliamsNY @naupaka @ahmedmoustafa and @kpoterlowicz - Just checking to see if you're planning on including this lesson in the June 2019 release. I know it will still be `alpha` at that point, but wasn't sure if you were planning on doing an official release on Zenodo or saving that for the `beta` release down the road. 

I know that, regardless of whether you're shooting for a full release, you're interested in getting community contributions, especially during the hackyday at the end of the month - so I'll go ahead and include this lesson as "provisional" in the list of lessons working towards the June release so that people know we're seeking contributions. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll do a first pass now as well and add some issues to the milestone. Let me know if you have any questions!

**Comment by ErinBecker** [comment]
I'm closing this issue as this lesson isn't ready for the June 2019 release.
