### ISSUE TITLE
data frame vs tibble in 4. Aggregating and Analyzing Data with dplyr

### ISSUE THREAD

**Issue by cbrueffer** [datacarpentry/genomics-r-intro#66]
Section `4. Aggregating and Analyzing Data with dplyr` talks about data frames, but all examples return tibbles. I think it would be helpful to have a short section which explains the main differences between the two.

**Comment by CreRecombinase** [comment]
I'm in the process of making a pull request about this, but might it make more sense to just stick with `tibbles` for the whole thing?  If we go all-in with loading `tidyverse` (as suggested in #21 ) instead of loading `dplyr`, we get `readr` for free, which means we can use `read_delim` instead of `read.table`.  That means the instructor is spared the distracting diversion into `stringsAsFactors`.  Right now the explanation/motivation of factors is simply introducing that they exist as a data type and mentioning they exist for the sake efficiency, (which isn't true). Moving to entirely `tibbles` (and `tidyverse`) frees up instructor time to either 1) give a proper motivation/explanation of factors by discussing categorical variables or 2) ignore factors entirely

**Comment by maglet** [comment]
I agree, the lessons should use tibbles throughout. so, use read_csv for the lesson instead of read.csv

**Comment by naupaka** [comment]
Should be addressed by changes in https://github.com/datacarpentry/genomics-r-intro/pull/96
