### ISSUE TITLE
Package load errors in website builds

### ISSUE THREAD

**Issue by ewallace** [datacarpentry/genomics-r-intro#92]
Hi,
There seem to be package loading errors in the current page builds:

* [Error in loadNamespace(name): there is no package called 'readxl'](https://datacarpentry.org/genomics-r-intro/03-basics-factors-dataframes/index.html)
* [Error in library("dplyr"): there is no package called 'dplyr'](https://datacarpentry.org/genomics-r-intro/04-dplyr/index.html)
* [Error in library(ggplot2): there is no package called 'ggplot2'](https://datacarpentry.org/genomics-r-intro/05-data-visualization/index.html)

I don't know how to fix that (unless someone knowledgeable can explain it to me), but it should be noted as an issue.

**Comment by naupaka** [comment]
@fmichonneau might know -- I don't think we're using Docker for these?

**Comment by zkamvar** [comment]
The reason for this is because while the scripts in the `bin/` folder have been updated, the `Makefile` has not. The solution is to update the Makefile with the one that's currently in the styles repo.

Specifically the problem is with the `lesson-md` rule:

https://github.com/datacarpentry/genomics-r-intro/blob/e97f1d8d4c7b2ade2527ee658fac2627ec394f0c/Makefile#L88-L92

In [the current version of the Makefile](https://github.com/carpentries/styles/blob/c4b6e237bddb95785b6e85282abef0479b6c60ab/Makefile#L122-L131), package installation is a separate rule that is added as a requirement for conversion to markdown:

```make
## * install-rmd-deps : Install R packages dependencies to build the RMarkdown lesson
install-rmd-deps:
	@${SHELL} bin/install_r_deps.sh


## * lesson-md        : convert Rmarkdown files to markdown
lesson-md : ${RMD_DST}


_episodes/%.md: _episodes_rmd/%.Rmd install-rmd-deps
	@mkdir -p _episodes
	@bin/knit_lessons.sh $< $@
```

**Comment by baileythegreen** [comment]
@zkamvar I was not seeing errors related to R packages not loading, but I suppose they were failing silently. Updating the Makefile in my fork did indeed work for rendering the markdown versions of the lessons.

There still seem to be some issues with the deploy step in both mine and EdCarp's fork, but looking at the datacarpentry repo's Action history, I don't think this step has been shown to work there, either? (Of course, due to a rogue PR earlier, the CI runs that support this statement have been buried beneath a bunch of others. Sorry.)

**Comment by fmichonneau** [comment]
Thanks for reporting this.
I believe that adba75ba3ca27b1856c75eb333f5807d10443b46 fixes the issue.

Regarding the deployment for forks, I have started a [Pull request](https://github.com/carpentries/lesson-example/pull/318) with instructions. Your feedback and comments would be appreciated.
